### ISSUE TITLE
Error in gen_all_res_list(count_bulk = bulk, ref_list = ref_list_beta,  :    argument "enableFileSaving" is missing, with no default.

### ISSUE THREAD

**Issue by HGT-UwU** [randel/scMD#1]
Hi, I'd like to report a bug which is stated in the title.
The function gen_all_res_list() from your other package EnsDeconv didn't set a default value for argument 'enableFileSaving'.

And I'd like to suggest that you can add an option in case someone don't want the output files but just estimated cell composition for function scMD(). Thanks.

**Comment by manqicai** [comment]
Hi, thank you for your response and your interest in scad. The updated version already fix the problem.
